import { Provider, ProviderConfig } from '../types';

// -- Provider defaults. All optional; leaving a key blank simply skips that provider.
// -- Free-tier friendly ones come first in the router pool.

export const DEFAULT_PROVIDERS: Record<Provider, ProviderConfig> = {
  gemini: {
    id: 'gemini',
    label: 'Google Gemini (free tier)',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    enabled: true,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['gemini-2.0-flash', 'gemini-2.5-flash', 'gemini-2.5-flash-lite'],
    defaultModel: 'gemini-2.0-flash',
  },
  groq: {
    id: 'groq',
    label: 'Groq (free tier, very fast)',
    baseUrl: 'https://api.groq.com/openai/v1',
    enabled: true,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768'],
    defaultModel: 'llama-3.3-70b-versatile',
  },
  cerebras: {
    id: 'cerebras',
    label: 'Cerebras (free tier, fastest)',
    baseUrl: 'https://api.cerebras.ai/v1',
    enabled: true,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['llama-3.3-70b', 'llama3.1-8b'],
    defaultModel: 'llama-3.3-70b',
  },
  openrouter: {
    id: 'openrouter',
    label: 'OpenRouter (has free models)',
    baseUrl: 'https://openrouter.ai/api/v1',
    enabled: true,
    dailyCount: 0,
    dailyResetAt: 0,
    models: [
      'deepseek/deepseek-chat-v3:free',
      'meta-llama/llama-3.3-70b-instruct:free',
      'google/gemini-2.0-flash-exp:free',
      'mistralai/mistral-nemo:free',
      'nousresearch/hermes-3-llama-3.1-405b:free',
    ],
    defaultModel: 'deepseek/deepseek-chat-v3:free',
  },
  mistral: {
    id: 'mistral',
    label: 'Mistral La Plateforme (free tier)',
    baseUrl: 'https://api.mistral.ai/v1',
    enabled: true,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['mistral-small-latest', 'open-mistral-nemo', 'ministral-8b-latest'],
    defaultModel: 'mistral-small-latest',
  },
  together: {
    id: 'together',
    label: 'Together AI (free credits)',
    baseUrl: 'https://api.together.xyz/v1',
    enabled: false,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['meta-llama/Llama-3.3-70B-Instruct-Turbo-Free', 'meta-llama/Llama-Vision-Free'],
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo-Free',
  },
  ollama: {
    id: 'ollama',
    label: 'Ollama (local, unlimited)',
    baseUrl: 'http://192.168.1.100:11434',
    enabled: false,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['llama3.1', 'llama3.2', 'mistral-nemo', 'qwen2.5', 'dolphin-mistral'],
    defaultModel: 'llama3.1',
  },
  openai: {
    id: 'openai',
    label: 'OpenAI (paid, fallback)',
    baseUrl: 'https://api.openai.com/v1',
    enabled: false,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['gpt-4o-mini', 'gpt-4o'],
    defaultModel: 'gpt-4o-mini',
  },
  anthropic: {
    id: 'anthropic',
    label: 'Anthropic Claude (paid, fallback)',
    baseUrl: 'https://api.anthropic.com/v1',
    enabled: false,
    dailyCount: 0,
    dailyResetAt: 0,
    models: ['claude-3-5-haiku-latest', 'claude-3-5-sonnet-latest'],
    defaultModel: 'claude-3-5-haiku-latest',
  },
};
